### ISSUE TITLE
Link colour in footer

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/docs#109]
Ouch my eyes! Can it be dark blue?

<img width="1279" alt="Screenshot 2021-07-29 at 09 35 49" src="https://user-images.githubusercontent.com/152863/127460262-6b0c8ff1-5749-409e-b3a2-458e7199554d.png">

**Comment by zebateira** [comment]
Should be. In what browser are you seeing this? Can't reproduce.

**Comment by alanshaw** [comment]
Firefox, and same in Chrome for me...

**Comment by zebateira** [comment]
Weird, it could be related to the regional cache issue in fleek. I'll talk to the team.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/2353186/127474127-ff21325e-3234-4d86-938f-0052cc635d21.png">

**Comment by zebateira** [comment]
@alanshaw could you inspect it for me since I can't debug? can you check what are the css rules of color being applied to those anchors?

**Comment by alanshaw** [comment]
<img width="1277" alt="Screenshot 2021-07-29 at 11 16 50" src="https://user-images.githubusercontent.com/152863/127475044-4042d63b-6894-4f36-a58f-f1c2f434129d.png">

**Comment by zebateira** [comment]
ooooh you have dark mode on! Forgot about that. On it!
