### ISSUE TITLE
JS Reference: client.list

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#113]
Add the new client.list method to our reference docs. 

The new client.list method was added in [this PR](https://github.com/web3-storage/web3.storage/pull/198). It uses the `GET /user/uploads` http endpoint under the hood. Oli updated the browser demo code to use it too, [here](https://github.com/web3-storage/web3.storage/pull/222). 

## Acceptance Criteria

- [ ]  client.list method for JS library is added
- [ ]  includes a description of parameters and output (digging into optional parameters and choices where needed)
- [ ]  A real-world example (showing some data passed in) is provided for each method
- [ ]  Has been proofed by a member of the Spark team for technical accuracy
- [ ]  Has been copy edited by someone who didn't write it

**THIS DOES NOT HAVE TO HIT LAUNCH DEADLINE.**

**Comment by johndmulhausen** [comment]
Done!
