### ISSUE TITLE
Document JS utilities library

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/docs#128]
We use the JS files-from-path library in the docs quickstart, but don't document it anywhere else. We should probably at least document [files-from-path](https://github.com/web3-storage/files-from-path) and [ipfs-car](https://github.com/web3-storage/ipfs-car), or at least link out to the READMEs on Github.

**Comment by yusefnapora** [comment]
There's a mention of files-from-path in the [store howto](https://docs.web3.storage/how-tos/store/#node.js), but I don't think we call out ipfs-car anywhere.

**Comment by dchoi27** [comment]
Thanks for the link. Maybe a page in the Reference section for links to the various utilities libraries? Or a line at the top of the JS client library reference?
