### ISSUE TITLE
Menu is longer than page content 

### ISSUE THREAD

**Issue by atopal** [web3-storage/docs#129]
Under some circumstances, the menu is longer than the main content area:

![Screenshot 2021-08-02 at 17 23 45](https://user-images.githubusercontent.com/557852/127893939-b6f1ae63-6b46-474b-a224-3bd90e5a8b68.png)

**Comment by jessicaschilling** [comment]
@terichadbourne Is this the sort of CSS issue you might be interested in troubleshooting in Ze's absence? No worries if not, just think you might be a lot quicker than me 😊

**Comment by jessicaschilling** [comment]
@terichadbourne - there's a fix in https://github.com/web3-storage/docs/pull/134 but it feels a bit hacky. Can you please take a look and see if you have any better thoughts (or merge if you feel it's acceptable)?
