### ISSUE TITLE
Link from docs to folder of examples in main repo

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#130]
@alanshaw could you please add the URL where you've put some examples that work in various frameworks, etc.?

**Comment by johnnymatthews** [comment]
[There's this folder here in web3-storage/web3-storage](https://github.com/web3-storage/web3.storage/tree/main/packages/client/examples). Is that the one you were thinking off @terichadbourne ?

**Comment by atopal** [comment]
That's the folder indeed
