### ISSUE TITLE
User testing pre-work for MVP launch

### ISSUE THREAD

**Issue by atopal** [web3-storage/docs#131]
Continuation of https://www.notion.so/protocollabs/d41b443683824f00b1c68161a49f7381?v=09e68a2deed7464baa95e8d4ba76f0cb&p=fd7b95b6e40542018c26915af108af02

Acceptance Criteria:
- [ ] User interview plan agreed on
- [ ] Recruiting set up for post MVP launch
- [ ] Conversation guides ready
- [ ] Screeners ready

**Comment by jessicaschilling** [comment]
@terichadbourne - noting that you moved this to Done, just noting that this doesn't actually close the issue - sorry!
