### ISSUE TITLE
Add HTTP API to reference section of docs

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/docs#136]
Know this has been floating around in conversations, but didn't see an issue for this yet. We should document the HTTP API as soon as possible to give developers flexibility in how they use web3.storage. Previously it sounded like the API might be changing a bit, but @alanshaw mentioned at this point it's not going to change drastically anytime soon - the main thing is creating the Open API schema (https://github.com/web3-storage/web3.storage/pull/145).

**Comment by terichadbourne** [comment]
Copying over some details from our Notion board as we transition to GitHub. This issue to get the HTTP API docs onto our docs site is blocked by web3-storage/web3.storage#145 which @johndmulhausen is already working on. 

## Acceptance Criteria

- Every method for the HTTP API is included
- Each method includes a description of parameters and output
- A real-world example (showing some data passed in) is provided for each example)
- Has been proofed by a member of the Spark team for technical accuracy
- Has been copy edited by someone who didn't write it
- Ideally: We're using ReDoc to publish the API reference based on the OpenAPI spec

**Comment by terichadbourne** [comment]
Note the 2 presentation options now proposed by @johndmulhausen in #151 (option 1) and #152 (option 2).
