### ISSUE TITLE
Show off community projects using web3.storage

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#147]
_From DAO M2 brainstorming_

Create some kind of user showcase, where we can list some cool/interesting stuff that folks have made using web3.storage.

If we wait until after ~Aug 10 we can fork the depersonalized ecosystem directory

Related: Highlight cool community activities / uses out in the wild - offer contest for the coolest one?

**Comment by dchoi27** [comment]
Closing for now, can revisit with broader growth strategy later
