### ISSUE TITLE
Explore presentation format for multi-language client libraries

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#149]
_From M2 DAO brainstorming_

If the API is OpenAPI compliant, we should get ahead of the issue of multi-language client libraries and how that works with a system like Redoc. (e.g. how do we present samples for multiple languages)
(you can delete this section after reading)

This needs further discussion, as I'm not sure which languages we expect to exist and how similar the methods will be across them to allow side-by-side presentation.

- [ ] one how-to has js and go exaples that you can tab between

**Comment by yusefnapora** [comment]
Reopening this now that #191 is on the table :)
