### ISSUE TITLE
Document `?filename` gateway query param in retrieval how-to

### ISSUE THREAD

**Issue by yusefnapora** [web3-storage/docs#154]
https://github.com/web3-storage/web3.storage/issues/325 reminded me that you can add a `?filename=name.ext` to an IPFS gateway URL so that the file gets downloaded using that filename. We should mention that in the retrieval how-to in the gateway section.

**Comment by atopal** [comment]
Should also go into troubleshooting, because most people will not upload files directly, instead they will use the JS client library that will wrap their file in a folder. Mention this in retrieval too.
