### ISSUE TITLE
How to generate the same CID for a file using Go-IPFS.

### ISSUE THREAD

**Issue by thewtex** [web3-storage/docs#155]
Hello :wave: ,

I am looking for documentation on how to generate the same CID via go-ipfs command line, e.g.

```
ipfs add --cid-version 1 [...]
```

possibly in the [Store How-To](https://docs.web3.storage/how-tos/store), so folks can pin with the same CID on services in addition to web.storage.

**Comment by atopal** [comment]
Should maybe go into the troubleshooting section

**Comment by thewtex** [comment]
From experimentation, this seems to work:

```
ipfs add -r --cid-version 1 --raw-leaves --hidden -s size-1048576 -w /my/file/path
```

Is there a flag that corresponds to `maxChildrenPerNode` here:

https://github.com/web3-storage/web3.storage/blob/3f6b6d38de796e4758f1dffffe8cde948d2bb4ac/packages/client/src/lib.js#L113

?

**Comment by johnnymatthews** [comment]
This would be super useful to add into the Troubleshooting section, but I'm getting different results to @thewtex:

I uploaded `pop-os_21.04_amd64_nvidia_7.iso` to Web3.Storage and got this CID back: `bafybeifdlpkkbyebtplmig4epkpcw363zp72kmzxgd6a6d6jkbn2berube`.

Then I ran the `ipfs add [...]` command suggested by @thewtex above, but got a different CID back:

```
ipfs add -r --cid-version 1 --raw-leaves -s size-1048576 -w ./pop-os_21.04_amd64_nvidia_7.iso

> added bafybeidm7dxpjwr34cqf6n3yy5vutyi6eka7ii5np6jx6ph5iemmomeqfi pop-os_21.04_amd64_nvidia_7.iso
> added bafybeihuwem6ikfp52xva3jgnkr4fjboc257wg75ukybi6cujb5l3oiuau
```

Might need an IPFS/Web3.Storage expert to weight-in here.

**Comment by thewtex** [comment]
It appears that the sharding capabilities of js-ipfs and go-ipfs are not get on par according to https://github.com/ipfs/go-ipfs/issues/7022 . Also, `shardSplitThreshold` and `maxChildrenPerNode` are different options here: https://www.npmjs.com/package/ipfs-unixfs-importer

**Comment by AugustoL** [comment]
Im having different file names here too. any update from the web3-storage team?

**Comment by AugustoL** [comment]
If you download the file from IPFS using CID 0
```
wget https://ipfs.io/ipfs/QmQ2r6iMNpky5f1m4cnm3Yqw8VSvjuKpTcK1X7dBR1LkJF/cat.gif
```
Or using CID 1:
```
wget https://bafybeigerijl5n4yp4air7tawbswpbraswhjwvj24mncooewhozp76x4am.ipfs.dweb.link/cat.gif
```

CID 0:
```
ipfs add -r --cid-version 0 -w cat.gif
added QmVracrju5M723tsMazcVCe3YTiG3D5TV1powDywLWHSyD cat.gif
added QmQ2r6iMNpky5f1m4cnm3Yqw8VSvjuKpTcK1X7dBR1LkJF 
```

CID 1:
```
ipfs add -r --cid-version 1 --raw-leaves -s size-1048576 -w cat.gif             
added bafybeif6sm4yzfnd7tgo5n26n2wljh6wmmiuvmesafktn4xx64h3pfry3q cat.gif
added bafybeigerijl5n4yp4air7tawbswpbraswhjwvj24mncooewhozp76x4am 
```

The same file is hosted with both CIDs, being able to be pass from CID 0 to 1. The name of the file matters, not only the content.

Can you confirm? :eyes:

**Comment by thewtex** [comment]
With `jsipfs` we are closer with:

```
jsipfs add --only-hash --pin=false --cid-version 1 -Q --chunker=size-1048576 --raw-leaves --cid-base=base32 -H -r -w .
```

But for larger datasets, we likely want the same `maxChildrenPerNode`.

**Comment by thewtex** [comment]
A related note, [the go-ipfs 0.11.0 improved HAMT-sharding support](https://github.com/ipfs/go-ipfs/releases/tag/v0.11.0).

**Comment by dchoi27** [comment]
Hey, hopefully this issue gives some insight into why the CIDs might be different: https://github.com/web3-storage/ipfs-car/issues/76

We're looking into more efficient ways of creating CAR files for writing to Web3.Storage (e.g., streaming) - and part of this will be updating the docs to be clear about what's happening under the hood.

One question from your original post - are you not able to pin data from Web3.Storage to other places using alternative CID encodings?

**Comment by thewtex** [comment]
@dchoi27 thanks for the information! Until that issue is addressed, it seems we should expect different CID's from Go-IPFS and JS-IPFS.

> One question from your original post - are you not able to pin data from Web3.Storage to other places using alternative CID encodings?

Yes, that is my current strategy -- I upload to Web3.Storage, then use that CID to pin on other providers. But, it would be helpful for data storage that is experimental or intended to be initially more temporary if this was not a requirement.
