### ISSUE TITLE
Add info about DDOS / spam mitigation to the docs

### ISSUE THREAD

**Issue by yusefnapora** [web3-storage/docs#168]
Prompted by a discussion in `#web3-storage` Filecoin slack:

<img width="747" alt="Screen Shot 2021-08-26 at 2 33 33 PM" src="https://user-images.githubusercontent.com/678715/131017597-aa4fb5cb-08c9-42ba-9613-d14091e765ff.png">

This issue is just to track the technical end - we can track the "how is it free" issue separately.

**Comment by atopal** [comment]
now handled in #269
