### ISSUE TITLE
Document go client

### ISSUE THREAD

**Issue by yusefnapora** [web3-storage/docs#191]
[go-w3s-client](https://github.com/web3-storage/go-w3s-client) is here 🎉 !

We should work it into the docs site. Ideally, we can pull it into all the How-to's as an alternative to JavaScript. That might need a little thinking about how to best present the alternatives though, so perhaps we should track that in a follow-on issue and focus on just telling people it exists first 😄 

As a first pass, let's say we want:

- [ ] A Go client reference page, or at minimum a sidebar link to the [pkg.go.dev docs](https://pkg.go.dev/github.com/web3-storage/go-w3s-client)
- [ ] A simple "hello web3.storage" go example we can put in the Examples section
- [ ] Updated copy in places where we talk about "the Web3.Storage client" in the singular

**Comment by dchoi27** [comment]
This is done!
