### ISSUE TITLE
[CONTENT REQUEST] (Sharing content)

### ISSUE THREAD

**Issue by beitmenotyou1** [web3-storage/docs#208]
I am a video editor, photographer and soon to be web/app designer, at the moment I am using opendrive for storing my staff and sharing things between clients

This is done by sharing an address with them that they can upload there stuff to that is stored on my drive and synced to my computer for me to edit for them

my suggestion is to add a similar thing where I can send them a link or IPFS protocol that they can open and then upload there stiff to for me to then download and edit

**Comment by atopal** [comment]
Hey there, while we are working on signed uploads, I don't think we'd want unauthorized people people upload unknown date. You might benefit from a product on top of web3.storage, maybe something like https://www.sliksafe.com ?
