### ISSUE TITLE
store to the same cid

### ISSUE THREAD

**Issue by cheehau** [web3-storage/docs#217]
is it possible to add new file to the same cid?

thanks

**Comment by dchoi27** [comment]
Hey there, it's not (this is a feature of IPFS - making immutable links to data). However, we just released an experimental feature for mutable records on Web3.Storage. You can check it out here: https://github.com/alanshaw/w3name 

Feedback is appreciated!

**Comment by dchoi27** [comment]
Hey! If ^ is of interest to you, this is probably a better place to get started: https://github.com/web3-storage/web3.storage/tree/main/packages/client#mutability

**Comment by dchoi27** [comment]
Closing for now, let us know if you have any questions
