### ISSUE TITLE
[PAGE ISSUE] Welcome

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/docs#42]
Warning that uploaded data is publicly available comes too late: 
![image](https://user-images.githubusercontent.com/11778450/126724495-49e2c4e2-227b-4cc2-bf93-72233b2e4f5d.png)

This should probably go in Step 5 in the previous section (`Create the upload script`) since that section tells users to upload their own arbitrary file

**Comment by johnnymatthews** [comment]
Good catch! Yeah this was meant to be _way_ higher up. No idea why I thought this was a good place for it.
