### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by atopal** [web3-storage/docs#59]
The package.json file in the quickstart guide has a specific author. During testing some people put their own names in, others left it as is. We might want to add something like "AUTHOR NAME", to clarify.

**Comment by jessicaschilling** [comment]
Note there are two instances where we list Vasco:
`/code-snippets/quickstart/package-example.json`
`/code-snippets/quickstart/package.json`
I assume we need to change both of these?

**Comment by jessicaschilling** [comment]
@terichadbourne @atopal https://github.com/web3-storage/docs/pull/94 fixes this. Can one of you please review and merge if OK?
