### ISSUE TITLE
Quickstart: Add info about multiple file upload 

### ISSUE THREAD

**Issue by atopal** [web3-storage/docs#60]
During testing people were delighted to find out that you can upload multiple files with the getting started script. We should add a line to let people know about that feature.

**Comment by terichadbourne** [comment]
@johnnymatthews Do you already know how this works? If so, could you please assign to yourself to call out that feature?

**Comment by jessicaschilling** [comment]
Is it just a matter of listing multiple instances of `filename` in this command?

![image](https://user-images.githubusercontent.com/1507828/127063251-ac453fb2-2b49-428b-9e54-abf0df6fca88.png)
