### ISSUE TITLE
Quickstart: script doesn't accept directories

### ISSUE THREAD

**Issue by atopal** [web3-storage/docs#63]
Code indicates that you can add directories, but that throws an error: 

```
❯ node upload.js .
Uploading files from .
file:///home/thattommyhall/FILES/node_modules/carbites/esm/lib/treewalk/splitter.js:42
      throw new Error(`missing block for ${ cid }`);
            ^
Error: missing block for bafybeidinerg4d2ltf7am3isuqdvjodes7lvkqpy7vwnrqq4grix6kh6ne
    at TreewalkCarSplitter._get (file:///home/thattommyhall/FILES/node_modules/carbites/esm/lib/treewalk/splitter.js:42:13)
    at async TreewalkCarSplitter._cars (file:///home/thattommyhall/FILES/node_modules/carbites/esm/lib/treewalk/splitter.js:54:19)
    at async TreewalkCarSplitter.cars (file:///home/thattommyhall/FILES/node_modules/carbites/esm/lib/treewalk/splitter.js:28:22)
    at async fillQueue (file:///home/thattommyhall/FILES/node_modules/streaming-iterables/dist/index.mjs:700:37)
```

**Comment by terichadbourne** [comment]
@yusefnapora @johnnymatthews  Do you already know how to fix this or do we need to call in the big guns?

**Comment by yusefnapora** [comment]
I can't seem to reproduce this...

```
node put-files.js --token="$w3stoken" ~/Pictures/token-images/memes\ \&\ gifs/
Uploading files from /Users/yusef/Pictures/token-images/memes & gifs/
Content added with CID: bafybeibskwkgomc6rmrmipijw2fzqzganfxcuyneq33oq35mwithaqchdi
```

[gateway link](https://bafybeibskwkgomc6rmrmipijw2fzqzganfxcuyneq33oq35mwithaqchdi.ipfs.dweb.link/)

@atopal does it always fail for you with directories?

**Comment by yusefnapora** [comment]
I did get a "too many open files" error when I tried uploading a random `node_modules` folder, but that looked different than the error shown above. Maybe the current directory is too big (possible because of a `node_modules` dir) and it's running out of memory?

**Comment by terichadbourne** [comment]
@yusefnapora Perhaps you could check the user testing vid if @atopal doesn't recall? Or perhaps @jessicaschilling recalls?

**Comment by jessicaschilling** [comment]
@yusefnapora @terichadbourne Sorry I can't provide more info on this. I was taking notes during the test sessions, so screen shares got a bit small for me to totally grok.

**Comment by terichadbourne** [comment]
Yusef is unable to reproduce and won't have time to address this today. Unassigning. 

@atopal  please let us know if you or Tommy can reproduce the error and document the steps leading up to it.

**Comment by atopal** [comment]
I'll ask Tom to comment.

**Comment by thattommyhall** [comment]
suspect I had `node_modules` in the folder, works ok for me with the files I wanted to try with in a seperate folder

**Comment by atopal** [comment]
Thank you very much @thattommyhall! Closing for now.
