### ISSUE TITLE
Make more mentions of this being a free service overall

### ISSUE THREAD

**Issue by jessicaschilling** [web3-storage/docs#73]
User testing participants expressed doubts that this service would _really_ be free, and exist for a long period of time.

Consider adding more "free!" language to docs as appropriate, and linking that language out to the main site's TOS page.

**Comment by terichadbourne** [comment]
@johndmulhausen Just removed your assignment here for the sake of making it available to whoever's available first after our P0-P2s, but if you're actively working on it feel free to add your face back and move to in progress.

**Comment by jessicaschilling** [comment]
@terichadbourne I'll add a few more mentions of "free".

**Comment by jessicaschilling** [comment]
https://github.com/web3-storage/docs/pull/108 should take care of this.
