### ISSUE TITLE
Quickstart: indicate in intro that you don't have to use node

### ISSUE THREAD

**Issue by jessicaschilling** [web3-storage/docs#74]
User testing participants experienced some friction in reading the quickstart if they weren't experienced JS/Node users: 
- "can I just call the API from something else?"
- "can I do this from the website?"

Consider adding language near the prerequisites section along the following lines: "This quickstart guide uses Node since it's so popular, but don't worry if that's not your primary way to get things done. Feel free just to skip to the (link) JS client library API reference or simply upload and retrieve files from the (link) Files page on your Web3.Storage account."

![image](https://user-images.githubusercontent.com/1507828/127068129-4072d55f-be18-4403-ae28-940541453ae0.png)

**Comment by terichadbourne** [comment]
Like this idea but might rephrase a bit to say Node is the fastest way to get set up to use the Web3.Storage JS Client programmatically, but you can reference the How to for nodeless options. If you want to skip the programming you can upload and retrieve files directly through the UI. (Not real sentences, just suggesting getting the most like things (programmatic ones) together.)

**Comment by terichadbourne** [comment]
@johnnymatthews Do you want to do this in the same PR as #72? If not I can reassign this to someone else to tackle separately.

**Comment by jessicaschilling** [comment]
@terichadbourne I'll grab it.
