### ISSUE TITLE
How To: Clarify browser retrieval as an option in retrieval how-to

### ISSUE THREAD

**Issue by jessicaschilling** [web3-storage/docs#76]
Some user testing respondents wondered if in-browser gateway view should get better play on the retrieval how-to, since it's so simple.
- [x] Consider moving it to the first item in this list
- [x] Either way, change text to "In your browser via an HTTP gateway."
![image](https://user-images.githubusercontent.com/1507828/127068756-33b8f505-281c-4756-bb5c-1e68501868ed.png)

**Comment by jessicaschilling** [comment]
@terichadbourne - #93 fixes this and is out for your review. Please merge if OK!

**Comment by terichadbourne** [comment]
@jessicaschilling is it intentional that we don't mention web3.storage/files as an option for retrieval? Otherwise this looks good!

**Comment by jessicaschilling** [comment]
@terichadbourne Good catch. I think the simplest way to do this is add it as a tip box, because we need to qualify that this only works for files you've uploaded (because that means they show on your Files page):
![image](https://user-images.githubusercontent.com/1507828/127193861-6654067e-fae3-42c3-aa45-8fd0ce628879.png)
