### ISSUE TITLE
ELSEWHERE: Inbound linking from IPFS docs

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#77]
## Acceptance Criteria

- [x]  A section about Filecoin and [Web3.Storage](http://web3.Storage) to the [persistence section](https://docs.ipfs.io/concepts/persistence/#persistence-versus-permanence) in IPFS Docs.  Per Pooja: "Decentralized storage isn’t a pinning service, exactly, so would be great to have a separate section about this, mention Filecoin as an option, and web3.storage as an easy way to use decentralized storage."
- [x]  Include links to relevant services (link to web3.storage website, not its docs)
- [x]  Callout appears like an aside in a relevant spot, not a heavy-handed attempt to divert traffic
- [x]  Reviewed and approved by Kadir & JV
- [ ]  **DO NOT MERGE** until after [web3.storage](http://web3.storage) is launched

## Executive approvals required

- Kadir
- JV

**Comment by johnnymatthews** [comment]
[Here's the working PR](https://github.com/ipfs/ipfs-docs/pull/847) that contains this content.

**Comment by johnnymatthews** [comment]
[PR is now ready for review](https://github.com/ipfs/ipfs-docs/pull/847)

**Comment by jessicaschilling** [comment]
This is out for (hopefully) final review in https://github.com/ipfs/ipfs-docs/pull/847 after a few rounds of revisions.

**Comment by jessicaschilling** [comment]
Per https://github.com/ipfs/ipfs-docs/pull/847#issuecomment-888598995 this should be OK to merge in the morning (North America) July 29. @terichadbourne, can you please push the button when you are ready?
