### ISSUE TITLE
[Blocked by design team] Update social card artwork

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#80]
Wait until MM makes another edit and ER approves as final, then... 

- [ ] Update social card on our site
- [ ] Open an issue or PR on main site to ensure it's flagged for Raf

Comment 206 on Figma: https://www.figma.com/file/826Zurcs6kgWSzQ35it966?node-id=1988:566#96827519

**Comment by jessicaschilling** [comment]
Pinged @ericronne and Martin to see what the latest is with this.
