### ISSUE TITLE
How To: Start-to-finish test (Thu AM)

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#82]
JS Dev who hasn't been through it before should be able to follow all steps described in store, retrieve and query how to sections with no tech blockers or major questions.

**Comment by johnnymatthews** [comment]
I haven't actually followed through these pages code-wise. Dunno if I qualify as a JS dev though, but I'll give it a shot.

**Comment by johnnymatthews** [comment]
Some suggestions:

## Store

- There isn't an example of how to create a data buffer of a file. Adding something like this under the **Preparing files for upload** section might mitigate super-noobs from getting stuck:

    ```javascript
    import { File, Web3Storage, getFilesFromPath} from 'web3.storage'
    let gondor_bytes = await getFilesFromPath('for-gondor.jpg')

    const files = [
        new File(['This is a public service announcement. This is only a test.'], 'plain-utf8.txt'),
        new File([gondor_bytes], 'for-gondor.jpg')
    ]
    ```

## Retrieve

- The user needs to install the client before they can retrieve anything:
    
    ```shell
    npm install web3.storage
    ```

- The `The Web3Response object` section returns an error for me:

    ```shell
    throw new Error(`Response was not ok: ${res.status} ${res.statusText} - Check for { "ok": false } on the Response object before calling .files`)
    ```

**Comment by terichadbourne** [comment]
@yusefnapora Do you have a sec to take a look at @johnnymatthews's notes above?

**Comment by johnnymatthews** [comment]
I can tackle the **Retrieve** notes by adding in the install bit and ripping out the section that's giving me an error. I'm not sure what to do with the **Store** section (the code I've put up there doesn't actually create a data buffer for the image).

**Comment by yusefnapora** [comment]
@johnnymatthews did you try this bit?

```js
function makeFileObjects() {
  const obj = { hello: 'world' }
  const buffer = Buffer.from(JSON.stringify(obj));

  const files = [
    new File(['contents-of-file-1'], 'plain-utf8.txt'),
    new File([buffer], 'hello.json')
  ]
}
```

It should hopefully make a file with the contents `{"hello":"world"}` - it's kind of hidden at the bottom of the node tab on "preparing your files".

**Comment by yusefnapora** [comment]
hmm, that should probably have a `return files` at the end.
