### ISSUE TITLE
Countly setup

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#83]
(Just copying over from Notion card so we can track here instead) 

## Acceptance Criteria

- [x]  Analytics are being populated on Countly
    - [x]  Docs #6 
    - [x]  Main Website (PR here: https://github.com/web3-storage/web3.storage/pull/126)
- [x]  Custom events tracked:
    - [x]  Docs
        - [x]  "Did you find this helpful?" button clicks (helpful/not helpful by page)
        - [x]  Most common header nav item clicks
        - [x]  Most common left nav item clicks
        - [x]  404s
        - [x]  Inbound traffic sources
    - [x]  Main website
        - [x]  Header links
        - [x]  Footer links
        - [x]  404s
        - [x]  Inbound traffic sources
        - See full **[Requirements for Main site](https://www.notion.so/storage-metrics-ee4ec19916e440e1aa3e3b0f2cc7030b)**
- [x]  New Countly App can be accessed through [~~https://countly.web3.storage~~](https://countly.web3.storage) [https://countly.protocol.ai](https://countly.protocol.ai)
    - ~~Infra to setup new DNS pointer & Countly team to issue new certificate~~
- [x]  Setup Dashboard with main stats and setup weekly email to be shared with appropriate stakeholders
    - [x]  Setup Dashboard
        - [x]  Docs
        - [x]  Main website
    - [x]  Setup weekly email report
        - [x]  Docs
        - [x]  Main website

**Comment by terichadbourne** [comment]
@zebateira Noticed you moved this to "review in progress" - do you have any PRs you need us to look at for you or other tasks you need help with?

**Comment by zebateira** [comment]
@terichadbourne no. The [PR to add countly to the main website](https://github.com/web3-storage/web3.storage/pull/126) is awaiting review, that's why I moved this issue to review. Or do you want to move it to review only when someone from our team reviews everything on countly?

**Comment by jessicaschilling** [comment]
@zebateira Looks like we are OK to close this? Can you please do so if that's true? 🙏

**Comment by jessicaschilling** [comment]
Ah, sorry - I thought that was taken care of. My bad.

**Comment by terichadbourne** [comment]
Final item on this is getting https://github.com/web3-storage/web3.storage/pull/126 merge after a review from @rafaelramalho19. Have confirmation from Oli that it's okay to delay the analytics until tomorrow.
