### ISSUE TITLE
Launch coordination tasks / final checks

### ISSUE THREAD

**Issue by terichadbourne** [web3-storage/docs#84]
Copied this over from the Notion card. @jessicaschilling @zebateira mind taking a look through to see if there's anything else already done or that you prefer to track in separate issues? Thanks!

## Acceptance Criteria

- [x]  Docs site DNS setup to point to [docs.web3.storage](http://docs.web3.storage)
- [x]  It launches at the same time as rest of website - meh, close enough
- [x]  All links between sites are functional - addressed in #69 
- [x]  All links within docs site are functional
- [x ]  All PRs on other sites with inbound links are only merged after [web3.storage](http://web3.storage) and [docs.web3.storage](http://docs.web3.storage) are live! - addressed in individual issues for docs site changes
- [x]  If determined OK, switch repo public
- [ ]  If repo switch public, reconfigure repo perms to remove any unnecessary access - caputured in 69
- [x]  Update repo readme, URL, etc - Teri opened a PR
- [x]  Use standard repo labeling scheme from [https://github.com/ipfs/community/blob/master/ISSUE_LABELS.md](https://github.com/ipfs/community/blob/master/ISSUE_LABELS.md)
- [x ]  Confirm Countly metrics are pulling in production data  - addressed in #69 
- [x]  Confirm social cards work correctly, including preview image
- [x ]  Do we need to add this to Google Search Console? (check with Andy?) tracked in 91

**Comment by jessicaschilling** [comment]
Maybe combine this issue with #69?

**Comment by terichadbourne** [comment]
Cool, accounting for these all elsewhere
