### ISSUE TITLE
How To: Update query code b/c `undefined` and `null` are different

### ISSUE THREAD

**Issue by olizilla** [web3-storage/docs#87]
In https://github.com/web3-storage/docs/blob/main/docs/how-tos/query.md#querying-for-status-information we recommend checking for `null`, but the api will return `undefined` in the case where there the cid provided is not a root cid for content that has been uploaded to web3.storage

The warning asks the user to check for `null` rather than `undefined` and the code sample does a loose equality check for `null` rather than `undefined` which works, but only because of the explicitly loose equality check.
```
const status = await client.status(cid)
if (status != null) {
  console.log(status)
}
```

An idomatic loosey goosey "hey this is js and it's cool" check for status being truthy (not false, null or undefined, [et al](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)) would be:

```
const status = await client.status(cid)
if (status) {
  console.log(status)
}
```

Or the strict check (`!==`) would be

```
const status = await client.status(cid)
if (status !== undefined) {
  console.log(status)
}
```

**Comment by olizilla** [comment]
it also feels slightly misleading to put a guard around a console.log, as you'd really want to log the status regardless of it's shape, so you can see when it's undefined in your console. I get that it was chose as a place holder for "your code goes here" but we want beginners to know it's ok to log the output of status regardless.

Perhaps
```js
const status = await client.status(cid)
console.log(status)
if (status) {
  // your code to do something fun with the status info here
}
 ```

**Comment by terichadbourne** [comment]
Thanks for the feedback and suggested replacement @olizilla!
